name: central

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'central/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Akka CLI
        uses: akka/setup-akka-cli-action@v1
        with:
          token: ${{ secrets.AKKA_TOKEN }}
          project-id: ${{ secrets.AKKA_PROJECT_ID }}

      - run: echo "Build & deploy central"

      - name: List projects
        run: akka projects list

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Push to local Docker
        run: mvn clean install -DskipTests
        working-directory: central

      - name: check docker
        run: docker images

      - name: akka service deployment
        run: akka service deploy central pharmacy-central:latest --pushâ€¨
      - name: check if akka service is exposed
        run: akka service get central